### PR TITLE
Modify the order of Chinaese name in ITSMIncidentProblemManagement

### PR DESCRIPTION
**Pull request by WEIBINBINXADT**
This branch fixes the order of the Chinese people's name for ITSMIncidentProblemManagement. Form Xian Dian Tong Software Co., Ltd., http://www.dian-tong.com/.

### CODE REVIEW

**Comment by UdoBretz** [comment]
Hello,

thanks for your pull request. But could you please first also send two pull request for OTRS 5 (and master). ITSMIncidentProblemManagement is based on OTRS 5, and without the same changes in OTRS 5 we would be out of sync.

Thanks, and bets regards,
Udo

**Comment by mgruner** [comment]
Hi @UdoBretz, we already merged the relevant changes in the framework, but only for master. rel-5_0 will not be updated. You should probably do the same.

**Comment by mgruner** [comment]
I guess this PR can be closed, because it only contains overridden files that will be updated when the modules are ported.

**Comment by UdoBretz** [comment]
Hi @mgruner,

currently OTRS::ITSM 5 is the master branch on ITSM, but based on  the rel-5_0 branch of OTRS. So right now, nothing needs to be done, as the changes will be included automatically as the master branch will be used for OTRS::ITSM 6 soon. Please feel free to close this PR.

**Pull request closed without merging**
